### ISSUE TITLE
Number of Pairs of Strings With Concatenation Equal to Target

### ISSUE THREAD

**Issue by jyoti-anjaly** [manisha069/HacktoberFest21#130]
Example:
Input: nums = ["123","4","12","34"], target = "1234", Here nums is a digit string.
Output: 2
Explanation: Valid pairs are:
- (0, 1): "123" + "4"
- (2, 3): "12" + "34"
I want to work on this issue in C++. Can you please assign me under Hacktoberfest 21.

**Comment by nishantkumar1308** [comment]
please assign it to me I will solve using C++

**Comment by manisha069** [comment]
No need of creating issues, please directly make a PR submitting the code.
