### ISSUE TITLE
A Bit more Organized 

### ISSUE THREAD

**Issue by pankajsingh016** [manisha069/HacktoberFest21#204]
Everything is Good. 
But there is no proper way of accessing any algorithm or code related to a  particular language in this repo.
@manisha069 Please assign this task to me

- [ ]  Making folder related to each language 
- [ ]  Shifting the particular file into those folders

**Comment by manisha069** [comment]
Thats a great issue that you've brought forward..is it possible that within Code and Algorithm folders to have distinct language folders as you suggest?

**Comment by pankajsingh016** [comment]
Yes, I would Like to contribute to this by making different folders of languages in these two folders.

**Comment by pankajsingh016** [comment]
![image](https://user-images.githubusercontent.com/69471864/135756887-b7cf1727-d42f-43ad-892b-7e94495e5d12.png)

I tried to clone this repo but there was some error.
I tried to resolve the error by command git reset and git lfs install to remove large file issue but the error is still there.

**Comment by manisha069** [comment]
@pankajsingh016 try again, should work now..

**Comment by pankajsingh016** [comment]
Worked! now Thank you @manisha069
