### ISSUE TITLE
Prim’s Minimum Spanning Tree Algorithm

### ISSUE THREAD

**Issue by JASKAMAL22** [manisha069/HacktoberFest21#313]
I would like to add source code of Prim's MST algo under the Python folder as a part of hacktoberfest.

**Comment by ganesh1729ganesh** [comment]
I want contribute the algorithm in c++. Please assign it to me.

**Comment by sejalsingh417** [comment]
I would like to do in java, please assign it to me

**Comment by manisha069** [comment]
No need to create issues, submit directly via PR.
First come first basis.
